//store all the to do list thats already exist on local storage
function get_todos(){
	var todos=new Array;
	var todos_str=localStorage.getItem('todo');
	if(todos_str !== null){
		todos=JSON.parse(todos_str);

	}
	return todos;

};
//to add the todo in localstorage
function add(){
	var task=document.getElementById('task').value;
	if(task===""){
		return false;
	}
	var todos=get_todos();
	todos.push(task);
	localStorage.setItem('todo',JSON.stringify(todos));
	show();
	clearDefault();

	// console.log(task);
	return false;//it will avoid any further action generated by click event
};

//once the task is add ,make the input box blank
function clearDefault(){
	document.getElementById('task').value="";
};
 //to delete the todo list item
 function remove(){
 	var id=this.getAttribute('id');
 	var todos=get_todos();
 	todos.splice(id,1);
 	localStorage.setItem('todo',JSON.stringify(todos));
 	show();
 	return false;
};
function show(){
	var todos=get_todos();
	var html="<ul>";
	for(var i=0;i<todos.length;i++){
		html += '<li>'+ todos[i]+ '<button class="remove" id=" '+i + '">Delete</button></li>';
	};
	html +='<ul>';
	document.getElementById('todos').innerHTML=html

	var buttons= document.getElementsByClassName('remove');
	for(var i=0;i< buttons.length; i++){
		buttons[i].addEventListener('click',remove);

	};
}
document.getElementById('add').addEventListener('click',add);
show();



